name: flow_custom_ui
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.5

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.3.4
  http: ^1.2.0
  youtube_player_iframe: ^5.2.0
  google_fonts: ^6.1.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "neondrop_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
