// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AiZaSyDpewGQWf0xa0lECEwO-Gwi6d1DK5VMmFg',
    authDomain: 'music-nova-2164b.firebaseapp.com',
    projectId: 'music-nova-2164b',
    storageBucket: 'music-nova-2164b.firebasestorage.app',
    messagingSenderId: '21226921183',
    appId: '1:21226921183:web:a3ac649f68851faca2dd6a',
    measurementId: 'G-GLJKHHX719',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AiZaSyDpewGQWf0xa0lECEwO-Gwi6d1DK5VMmFg',
    authDomain: 'music-nova-2164b.firebaseapp.com',
    projectId: 'music-nova-2164b',
    storageBucket: 'music-nova-2164b.firebasestorage.app',
    messagingSenderId: '21226921183',
    appId: '1:21226921183:web:a3ac649f68851faca2dd6a',
    androidClientId: '21226921183-7sfl7o49a4rttqa17a5kn5ghddrtbrda.apps.googleusercontent.com',
  );
}
